---
title: "index.Rmd"
author: "Piet Stam"
date: "27-7-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

```{r plot}

source("global.R")

db1 <- skater_35474_500
db2 <- skater_14920_500
  
plot.title = "title"
plot.subtitle = "Data source: speedskatingresults.com, adjusted for difference in birth dates"

library(plotly)
pl <- plot_ly(
  type='scatter',
  mode='line',
  x=db1$times.date,
  y=strftime(db1$times.time, format="%M:%S"),
  name=skaters_id[skaters_id["id"] == db1$skater[1]][2]
)
  
pl <- pl %>% add_trace(
  type='scatter',
  mode='line',
  x=db2$times.date,
  y=strftime(db2$times.time, format="%M:%S"),
  name=skaters_id[skaters_id["id"] == db2$skater[1]][2]
) 

pl <- pl %>% 
  layout(title = paste0(plot.title,"<BR>",plot.subtitle),
         xaxis = list(title = ""),
         yaxis = list(title = "Best monthly track times"),
         legend=list(title=list(text='<b> Speed skaters </b>'), x = 0.8, y = 0.8)
)

pl <- pl %>% 
  layout(
    updatemenus = list(
      list(
        y = 0.7,
        buttons = list(
          list(method = "restyle",
               args = list("y", list(df$y)),  # put it in a list
               label = "Show A"),
          list(method = "restyle",
               args = list("y", list(df$z)),  # put it in a list
               label = "Show B")))
    )
)

pl

```